sudo: false
language: ruby
bundler_args: --without tools
before_install:
  - gem install bundler
cache: bundler
rvm:
  - 2.3.1
  - 2.4.3
  - 2.5.0
  - 2.6.2
notifications:
  email:
    - kirill.tatchihin@craft.co
    - alex.klimenkov@craft.co
script: bundle exec rake test
